face_detection/app/urls.py
# Fichier urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('searchCustomer',views.searchCustomer, name='search_c'),
    path('listCustomers', views.listCustomers, name='list_c'),
    path('addCustomer', views.addCustomer, name='add_c'),
]
#    path('showCustomer', views.searchCustomer, name='show_c'),

face_detection/face_detection/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

face_detection/app/models.py
from django.db import models
#from django.utils import timezone


# Customer table
class Customer(models.Model):
    boolChoice = (("Male","Male"),("Female","Female"))
    balcklistChoice = (("Yes", "Yes"), ("No", 'No'))

    customer_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    age = models.PositiveIntegerField(blank=True, null=True)
    isBlackList = models.CharField(max_length = 3,choices=balcklistChoice)
    gender = models.CharField(max_length = 6,choices=boolChoice)
    image = models.ImageField(upload_to='images')

    def str(self):
        return '%s %s' % (self.first_name, self.last_name)

    def unicode(self):
        return '%s %s' % (self.first_name, self.last_name)

# # Model Accident
# class Incident(models.Model):
#     # accident_id = models.AutoField(primary_key=True)
#     label = models.CharField(max_length=120)

#     def str(self):
#         return self.label

# Each image is converted on embedding vector and stored in BDD as vector 
# class EmbeddingVectors(models.Model):
#     ev_id = models.AutoField(primary_key=True)
#     link_file = models.CharField(max_length=10000)
#     person_ev = models.ForeignKey(Customer, related_name="person_ev", on_delete=models.CASCADE, db_column='customer_id')


# class VisitsHistory(models.Model):
#     # visit_id = models.AutoField(primary_key=True)
#     entry_date = models.DateTimeField(editable=False)
#     exit_date = models.DateTimeField()
#     total_spent = models.FloatField()
#     person_vh = models.ForeignKey(Customer, related_name="person_vh", on_delete=models.CASCADE, db_column='person_id')

#     def init(self, *args, kwargs):
#         # super().init(args, kwargs)
#         self.id = None

#     def save(self, *args, kwargs):
#         """ On save, update timestamps """
#         if not self.id:
#             self.entry_date = timezone.now()
#         # self.entry_date_modified = timezone.now()
#         return super(VisitsHistory, self).save(*args, kwargs)

#     def save_exit(self, *args, kwargs):
#         """ On save, update timestamps """
#         if self.id:
#             self.exit_date = timezone.now()
#         # self.exit_date_modified = timezone.now()
#         return super(VisitsHistory, self).save(*args, **kwargs)


# class Association(models.Model):
#     association_id = models.AutoField(primary_key=True)
#     accident_id = models.ForeignKey(Incident, related_name="accident_id", on_delete=models.CASCADE,
#                                     db_column='accident_id')
#     visit_id = models.ForeignKey(VisitsHistory, related_name="visit_id", on_delete=models.CASCADE,
#                                  db_column='visit_id')
#     description = models.TextField(blank=True, null=True)
#     damages_estimation = models.FloatField()

#     class Meta:
#         managed = True
#         db_table = 'association'
#         unique_together = (('accident_id',
#                             'visit_id'),)

#     def str(self):
#         return self.description

face_detection/app/templates/home/addCustomer.html
{% extends 'base.html' %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Records</title>

    </head>

    <body>
      {% block content %}
      <main role="main" class="container">
        <div class="jumbotron text-center">

        <div class="form-group row">
        <label class="col-sm-2 col-form-label"><b>Enter customer's infos :</b></label>
        <div class="col-sm-4">
            <form method="POST" class="post-form" enctype="multipart/form-data">
              {% csrf_token %}
                <div class="col-sm-4">
               <!-- <input type="number" name="id", required maxlength="254"  /> -->
               {{ form.as_p }}
               <div class="col-sm-4">
                <button type="submit" class="btn btn-success">Add customer</button>
                </div>
             </form>

             {% if img_obj %}
               <h3>Succesfully uploaded : {{img_obj.first_name}}</h3>
               <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">
             {% endif %}
        </div>
        </div>

      </div>
      </main>
      
  
<!-- 
          <div class="form-group col">
                <label class="col-sm-2 col-form-label"> Prénom:</label>
                <div class="col-sm-4">
                  <b>{{ employee.prenom }}</b>
                </div>
          </div>
     <div class="form-group col">
            <label class="col-sm-2 col-form-label"> Nom:</label>
            <div class="col-sm-4">
              <b>{{ employee.nom }}</b>
            </div>

          </div>
          <div class="form-group col">
            <label class="col-sm-2 col-form-label"> Age :</label>
            <div class="col-sm-4">
              <b>{{ employee.age }}</b>
            </div>
          </div>

          <div class="form-group col">
            <label class="col-sm-2 col-form-label">Poste:</label>
            <div class="col-sm-4">
              <b>{{ employee.poste }}</b>
            </div>
          </div>
        </div>
          <div class="form-group col">
            <label class="col-sm-2 col-form-label">Ville:</label>
            <div class="col-sm-4">
              <b>{{ employee.ville }}</b>
            </div>
    
          </div>
    
          <div class="form-group col">
            <label class="col-sm-2 col-form-label">Salaire:</label>
            <div class="col-sm-4">
              <b>{{ employee.salaire }}</b>
            </div>
          </div>
    
          <div class="form-group col">
            <label class="col-sm-2 col-form-label">Département:</label>
            <div class="col-sm-4">
              <b>{{ employee.departement }}</b> -->
            <!-- </div> -->

      {% endblock %}
    </body>
    </html>

face_detection/app/templates/home/existsCustomer.html
{% extends 'base.html' %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Records</title>

    </head>

    <body>
      {% block content %}
      <main role="main" class="container">
        <div class="jumbotron text-center">
          <h1> This customer already extists </h1>
          <br>
          <br>
          <a href="/addCustomer"  class="btn btn-primary"> Return to add new customer</a>
        </div>
    
    
    </main>

      {% endblock %}
    </body>
    </html>

face_detection/app/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
<main role="main" class="container">
    <div class="jumbotron text-center">
        <h1>Night Club Strasbourg All Night</h1>
        <p class="lead text-info">Customers </p>
        <br>
        <br>
        <img src="\static\images\image_party.jpg" >
        <br>
        <br>
        <a href="https://github.com/kadi-hocine" target="_blank">Github</a>
    </div>


</main>
{% endblock %}

face_detection/app/templates/home/listCustomers.html
{% extends 'base.html' %}
<!DOCTYPE html>  
    <html lang="en">  
    <head>  
        <meta charset="UTF-8">  
        <title>Records</title>

    </head>  
    <body>  
        
    {% block content %}
    <table class="table table-striped table-bordered table-sm">  
        <thead class="thead-dark">  
        <tr>  
            <th>Customer Id </th>
            <th>Customer first name </th>
            <th>Customer last name </th>
            <th>Customer age </th>
            <th>Customer gender </th>
            <th>Blacklist Yes/No</th>  
            <th>Customer image </th>  
          
        </tr>  
        </thead>  
        <tbody>  
    {% for customer in customers %}  
        <tr>  
            <td>{{ customer.customer_id }}</td>
            <td>{{ customer.first_name }}</td>
            <td>{{ customer.last_name }}</td>
            <td>{{ customer.age }}</td>
            <td>{{ customer.gender }}</td>
            <td>{{ customer.isBlackList }}</td>
            <td><img src={{ customer.image }}></td>

            <td>  

            </td>  
        </tr>  
    {% endfor %}  
        </tbody>  
    </table>  
    <br>  
    <br>  
    <center><a href="/addCustomer" class="btn btn-primary">Add a new customer</a></center>
    {% endblock %}
    </body>  
    </html>  

face_detection/app/templates/home/notexistsCustomer.html
{% extends 'base.html' %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Records</title>

    </head>

    <body>
      {% block content %}
      <main role="main" class="container">
        <div class="jumbotron text-center">
          <h1> Any customer in the database </h1>
          <br>
          <br>
          <a href="/addCustomer"  class="btn btn-primary"> Return to add this new customer</a>
        </div>
    
        <table class="table table-striped table-bordered table-sm">  
          <thead class="thead-dark">  
          <tr>  
   
              <th>List of detected persons </th>  
            
          </tr>  
          </thead>  
          <tbody>  
      {% for customer_out in customers_out %}  
          <tr>  
              <td><img src={{ customer_out }}></td>
          </tr>  
      {% endfor %}  
          </tbody>  
      </table>  
    </main>

      {% endblock %}
    </body>
    </html>

face_detection/app/templates/home/searchCustomer.html
{% extends 'base.html' %}
 <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Forms</title>
        {% load static %}
        <!-- <link rel="stylesheet" href="{% static 'css/beautiful.css' %}"/> -->
    </head>
    <body>
      {% block content %}
      <main role="main" class="container">
        <div class="jumbotron text-center">

      
    <div class="form-group raw">
        <label class="raw-lg-6 raw-form-label"></label>
        <div class="raw-lg-6">
            <h1>Search a customer</h1>
        </div>
      

        <div class="form-group col">
          <label class="row-lg-2 row-form-label-lg">Upload customer's image :</label>
          <div class="row-sm-4">
              <form method="POST" name ='image' class="post-form" enctype="multipart/form-data">
                {% csrf_token %}
                  <div class="col-sm-4">
                 {{ form2.as_p }}
                 <div class="col-sm-4">
                  <button type="submit" class="btn btn-success">search customer</button>
                  </div>
               </form>
  
          </div>
          </div>
  
        </div>

        {% if customers_in %}
        <table class="table table-striped table-bordered table-sm">  
          <thead class="thead-dark">  
          <tr>  
              <th>Customer Id </th>
              <th>Customer first name </th>
              <th>Customer last name </th>
              <th>Customer age </th>
              <th>Customer gender </th>
              <th>Blacklist Yes/No</th>  
              <th>Customer image </th>  
            
          </tr>  
          </thead>  
          <tbody>  
      {% for customer in customers_in %}  
          <tr>  
              <td>{{ customer.customer_id }}</td>
              <td>{{ customer.first_name }}</td>
              <td>{{ customer.last_name }}</td>
              <td>{{ customer.age }}</td>
              <td>{{ customer.gender }}</td>
              <td>{{ customer.isBlackList }}</td>
              <td><img src={{ customer.image }}></td>
  
              <td>  
  
              </td>  
          </tr>  
      {% endfor %}  
          </tbody>  
      </table>  
      {% endif %}

      {% if customers_out %}
      <table class="table table-striped table-bordered table-sm">  
        <thead class="thead-dark">  
        <tr>  
 
            <th>List of people not in the database </th>  
          
        </tr>  
        </thead>  
        <tbody>  
    {% for customer_out in customers_out %}  
        <tr>  
            <td><img src={{ customer_out }}></td>
        </tr>  
    {% endfor %}  
        </tbody>  
    </table>  



      <!-- old form 
        <div class="form-group row">
            <label class="col-sm-2 col-form-label"> First name:</label>
            <div class="col-sm-4 col-form-label-lg">
              {{ customer.first_name }}
            </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label"> Last name:</label>
        <div class="col-sm-4 col-form-label-lg">
          {{ customer.last_name }}
        </div>
        <br>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label"> Age :</label>
        <div class="col-sm-4 col-form-label-lg">
          {{ customer.age }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Blacklist Yes/No:</label>
        <div class="col-sm-4 col-form-label-lg">
          {{ customer.isBlackList }}
        </div>
      </div>
    </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Gender:</label>
        <div class="col-sm-4 col-form-label-lg">
          {{ customer.gender }}
        </div>

      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Image:</label>
          <img src={{ customer.image }}>
      </div> -->

      {% endif %}
      </main>

    {% endblock %}
    </body>
    </html>

face_detection/app/templates/home/updateEmploye.html
{% extends 'base.html' %}
<!DOCTYPE html>  
    <html lang="en">  
    <head>  
        <meta charset="UTF-8">  
        <title>Index</title>  
    </head>  
    <body>  
      {% block content %}


    <form method="POST" class="post-form" >
            {% csrf_token %}  
      <div>
            <main role="main" class="container">
              <div class="jumbotron text-center">
                  <h1>Modifier les informations des employés</h1>
              </div>
          </main>
      
      <div class="form-group col">  
        <label class="col-sm-2 col-form-label">Prénom:</label>
        <div class="col-sm-4">  
            <input type="text" name="prenom" id="id_ename" required maxlength="100" value="{{ employee.prenom }}" />
        </div>  
      </div>  

        <div class="form-group col">  
        <label class="col-sm-2 col-form-label">Nom:</label>
        <div class="col-sm-4">  
            <input type="text" name="nom" id="id_nom" required maxlength="254" value="{{ employee.nom }}" />
        </div>  
      </div>  

        <div class="form-group col">  
        <label class="col-sm-2 col-form-label">Ville:</label>
        <div class="col-sm-4">  
            <input type="text" name="ville" id="id_ville" required maxlength="15" value="{{ employee.ville }}" />
        </div>  
      </div>

      <div class="form-group col">
        <label class="col-sm-2 col-form-label">Salaire:</label>
        <div class="col-sm-4">
            <input type="number" name="salaire" id="id_salaire" required maxlength="15" value="{{ employee.salaire }}" />
        </div>
      </div>

      <div class="form-group col">
        <label class="col-sm-2 col-form-label">Age:</label>
        <div class="col-sm-4">
            <input type="number" name="age" id="id_age" required maxlength="15" value="{{ employee.age }}" />
        </div>
      </div>

      <div class="form-group col">
        <label class="col-sm-2 col-form-label">Poste:</label>
        <div class="col-sm-4">
            <input type="text" name="poste" id="id_poste" required maxlength="15" value="{{ employee.poste }}" />
        </div>
      </div>

      <div class="form-group col">
        <label class="col-sm-2 col-form-label">Département:</label>
        <div class="col-sm-4">
            <input type="number" name="departement" id="id_department" required maxlength="15" value="{{ employee.departement_id }}" />
            <br>
            <p>Le département {{ employee.departement_id }} correspond au : {{ employee.departement}}</p>
        </div>
      </div>

        <div class="form-group col">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <button type="submit" class="btn btn-success">Modifier</button>  
        </div>  
      </div>  

        </div>  
    </form>  
    {% endblock %}
    </body>  
    </html>  